/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRzovS3VsaWFoL1RJLTJFL1BlbXJvZ3JhbWFuIFdFQiBsYW5qdXQvQmVsYWphckFuZ3VsYXIvUHJhazEvcHJhazQvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0c6L0t1bGlhaC9USS0yRS9QZW1yb2dyYW1hbiBXRUIgbGFuanV0L0JlbGFqYXJBbmd1bGFyL1ByYWsxL3ByYWs0L3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
