/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRzovS3VsaWFoL1RJLTJFL1BlbXJvZ3JhbWFuIFdFQiBsYW5qdXQvQmVsYWphckFuZ3VsYXIvUHJhazEvcHJhazQvc3JjL2FwcC9uYXZiYXIvbmF2YmFyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRzovS3VsaWFoL1RJLTJFL1BlbXJvZ3JhbWFuIFdFQiBsYW5qdXQvQmVsYWphckFuZ3VsYXIvUHJhazEvcHJhazQvc3JjL2FwcC9uYXZiYXIvbmF2YmFyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
