/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRzovS3VsaWFoL1RJLTJFL1BlbXJvZ3JhbWFuIFdFQiBsYW5qdXQvQmVsYWphckFuZ3VsYXIvUHJhazEvcHJhazQvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9HOi9LdWxpYWgvVEktMkUvUGVtcm9ncmFtYW4gV0VCIGxhbmp1dC9CZWxhamFyQW5ndWxhci9QcmFrMS9wcmFrNC9zcmMvYXBwL2FwcC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
